controllers/PaymentController.php
<?php

namespace app\controllers;


use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class PaymentController extends Controller
{
    private const BANK_API_URL = 'https://api.bank.boo';

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['send', 'update-user-balance', 'convert', 'money-to-points'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'send' => ['POST'],
                    'convert' => ['GET'],
                    'update-user-balance' => ['POST'],
                    'money-to-points' => ['POST'],
                ],
            ],
        ];
    }

    public function actionSend()
    {
        $params = Yii::$app->request->post();

        try {
            $client = new \GuzzleHttp\Client();
//            $client->request('POST', BANK_API_URL, ['query' => [
//                'bank_account' => $params['bank_account'],
//                'sum' => $params['sum'],
//            ]]);
        } catch (\Exception $e) {
            Yii::error([
                'method' => 'something wrong',
                'error' => $e->getMessage(),
            ]);
            return \yii\helpers\Json::encode(['status' => false]);
        }

        return \yii\helpers\Json::encode(['status' => true]);
    }

    public function actionUpdateUserBalance()
    {
        $params = Yii::$app->request->post();
        $user = User::findIdentity(Yii::$app->user->id);

        if (is_null($user)) {
            Yii::error([
                'method' => 'User not found',
            ]);
            return \yii\helpers\Json::encode(['status' => false]);
        }

        if ($params['reward_id'] == 1) {
            $user->cash = $user->cash + $params['sum'];
        } elseif ($params['reward_id'] == 2) {
            $user->points = $user->points + $params['sum'];
        }

        try {
            $user->save();
        } catch (\Exception $e) {
            Yii::error([
                'error' => $e->getMessage(),
            ]);
            return \yii\helpers\Json::encode(['status' => false]);
        }

        return \yii\helpers\Json::encode(['status' => true]);
    }

    /**
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionConvert()
    {
        $user = User::findIdentity(Yii::$app->user->id);

        if (is_null($user)) {
            Yii::error([
                'method' => 'User not found',
            ]);
            throw new NotFoundHttpException('User not found');
        }

        return $this->render('convert', compact('user'));
    }

    public function actionMoneyToPoints()
    {
        $params = Yii::$app->request->post();
        $user = User::findIdentity(Yii::$app->user->id);
        $convertedSum = $params['money'];
        $percentage = 30;

        if (is_null($user)) {
            Yii::error([
                'method' => 'User not found',
            ]);
            return \yii\helpers\Json::encode(['status' => false]);
        }

        $commission = ($percentage / 100) * $convertedSum;

        $newCash = $user->cash - $convertedSum;
        $newPoints = $user->points + round($convertedSum - $commission);

        User::updateAll([
            'cash' => $newCash,
            'points' => $newPoints
        ], [
            'id' => $user->id
        ]);

        Yii::$app->db->getLastInsertID();

        return \yii\helpers\Json::encode([
            'status' => true,
            'money' => $newCash,
            'points' => $newPoints,
        ]);
    }

}

views/payment/convert.php
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        let money = $('[name="money"]');

        $('[name="convertForm"]').submit(function (e) {
            e.preventDefault();

            $.ajax({
                url: '/payment/money-to-points',
                type: 'post',
                dataType: 'json',
                data: {
                    money: money.val(),
                    _csrf: yii.getCsrfToken()
                },
                success: function (data) {
                    if (data.status === true) {
                        $('.cash').empty().append(data.money);
                        $('.points').empty().append(data.points);
                    }
                }
            });
        });
    });
</script>

<?php

/* @var $this yii\web\View */

use \yii\helpers\Html;

$this->title = 'Casexe test';

?>
<div class="site-index">

    <h1>Конвертация $ в Баллы</h1>

    <div class="body-content">
        <form method="post" name="convertForm">
            <div class="row-fluid">
                На вашем счете $<span class="cash"><?= $user->cash ?></span> и <span class="points"><?= $user->points ?></span> баллов
            </div>
            <div class="row-fluid">
                <input type="number" name="money" min="1" max="<?= $user->cash ?>">
            </div>

            <div class="row-fluid" style="margin-top: 2em;">
                <input type="submit" class="btn btn-success" value="Конвертировать">
            </div>

        </form>
    </div>
</div>

<!-- Transafer Modal -->
<div class="modal transferModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content" style="padding: 1.5em;">
            <div class="modal-body">
                <div class="row-fluid">
                    <form class="mt-3" name="transferForm">
                        <div class="row-fluid">
                            <input type="text" name="bank_account" class="form-control" placeholder="счет в банке">
                        </div>
                        <div class="row-fluid">
                            <div class="input-group">
                                <button class="btn btn-success cert-button bank_request">отправить выигрыш</button>
                            </div>
                        </div>
                        <div class="mt-2 row-fluid">
                            <div>Нажимая на кнопку "Записаться", я даю согласие
                                на обработку персональных данных и соглашаюсь
                                c условиями договора-оферты и политикой защиты
                                персональных данных
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end Transafer Modal -->