controllers/ParcelController.php
<?php
namespace app\controllers;


use app\models\Parcel;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;

class ParcelController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['shipping'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'shipping' => ['POST']
                ],
            ],
        ];
    }

    public function actionShipping()
    {
        $params = Yii::$app->request->post();

        try {
            $parcel = new Parcel();
            $parcel->user_id = Yii::$app->user->id;
            $parcel->thing_id = $params['thing_id'];
            $parcel->address = $params['address'];

            $parcel->save();
        } catch (\Exception $e) {
            Yii::error([
                'method' => 'something wrong',
                'error' => $e->getMessage(),
            ]);
            return \yii\helpers\Json::encode(['status' => false]);
        }

        return \yii\helpers\Json::encode(['status' => true]);
    }
}

controllers/PaymentController.php
<?php

namespace app\controllers;


use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

class PaymentController extends Controller
{
    private const BANK_API_URL = 'https://api.bank.boo';

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['send', 'update-user-balance', 'convert', 'money-to-points'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'send' => ['POST'],
                    'convert' => ['GET'],
                    'update-user-balance' => ['POST'],
                    'money-to-points' => ['POST'],
                ],
            ],
        ];
    }

    public function actionSend()
    {
        $params = Yii::$app->request->post();

        try {
            $client = new \GuzzleHttp\Client();
//            $client->request('POST', BANK_API_URL, ['query' => [
//                'bank_account' => $params['bank_account'],
//                'sum' => $params['sum'],
//            ]]);
        } catch (\Exception $e) {
            Yii::error([
                'method' => 'something wrong',
                'error' => $e->getMessage(),
            ]);
            return \yii\helpers\Json::encode(['status' => false]);
        }

        return \yii\helpers\Json::encode(['status' => true]);
    }

    public function actionUpdateUserBalance()
    {
        $params = Yii::$app->request->post();
        $user = User::findIdentity(Yii::$app->user->id);

        if (is_null($user)) {
            Yii::error([
                'method' => 'User not found',
            ]);
            return \yii\helpers\Json::encode(['status' => false]);
        }

        if ($params['reward_id'] == 1) {
            $user->cash = $user->cash + $params['sum'];
        } elseif ($params['reward_id'] == 2) {
            $user->points = $user->points + $params['sum'];
        }

        try {
            $user->save();
        } catch (\Exception $e) {
            Yii::error([
                'error' => $e->getMessage(),
            ]);
            return \yii\helpers\Json::encode(['status' => false]);
        }

        return \yii\helpers\Json::encode(['status' => true]);
    }

    /**
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionConvert()
    {
        $user = User::findIdentity(Yii::$app->user->id);

        if (is_null($user)) {
            Yii::error([
                'method' => 'User not found',
            ]);
            throw new NotFoundHttpException('User not found');
        }

        return $this->render('convert', compact('user'));
    }

    public function actionMoneyToPoints()
    {
        $params = Yii::$app->request->post();
        $user = User::findIdentity(Yii::$app->user->id);
        $convertedSum = $params['money'];
        $percentage = 30;

        if (is_null($user)) {
            Yii::error([
                'method' => 'User not found',
            ]);
            return \yii\helpers\Json::encode(['status' => false]);
        }

        $commission = ($percentage / 100) * $convertedSum;

        $newCash = $user->cash - $convertedSum;
        $newPoints = $user->points + round($convertedSum - $commission);

        User::updateAll([
            'cash' => $newCash,
            'points' => $newPoints
        ], [
            'id' => $user->id
        ]);

        Yii::$app->db->getLastInsertID();

        return \yii\helpers\Json::encode([
            'status' => true,
            'money' => $newCash,
            'points' => $newPoints,
        ]);
    }

}

controllers/RewardController.php
<?php

namespace app\controllers;


use app\models\Reward;
use app\models\RewardUser;
use app\models\Thing;
use app\models\User;
use yii\data\ActiveDataProvider;
use yii\db\ActiveRecord;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use Yii;
use yii\web\NotFoundHttpException;

/**
 * Class RewardController
 * @package app\controllers
 *
 * @property Thing $thing
 */
class RewardController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['generate', 'cancel-reward'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'generate' => ['POST'],
                    'cancel-reward' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * @return string
     * @throws \Exception
     */
    public function actionGenerate()
    {
        $reward = $this->getReward();

        return \yii\helpers\Json::encode($reward);
    }

    /**
     * @return string
     * @throws \Exception
     */
    public function actionCancelReward()
    {
        $params = Yii::$app->request->post();
        $userId = Yii::$app->user->id;

        try {
            RewardUser::updateAll([
                'cancelled' => 1
            ], [
                'reward_id' => $params['reward_id'],
                'user_id' => $userId
            ]);
        } catch (\Exception $e) {
            Yii::error([
                'message' => $e->getMessage()
            ]);
            return \yii\helpers\Json::encode(['status' => false]);
        }

        return \yii\helpers\Json::encode(['status' => true]);
    }

    /**
     * @return array|bool
     * @throws \Exception
     */
    private function getReward()
    {
        $reward_qty = 0;
        $user = User::findOne(Yii::$app->user->id);

        $reward = Reward::getAvailable();

        if (is_null($reward)) {
            Yii::error([
                'message' => 'rewards not found'
            ]);
            return false;
        }

        if ($reward->type == Reward::MONEY) {

            $delta = $reward->total - $reward->gifted_qty;

            if ($delta > $reward->to) {
                $reward_qty = $this->getRewardSize($reward->from, $reward->to);
            } else {
                $reward_qty = $this->getRewardSize($reward->from, $delta);
            }

            $this->updateGiftedQty($reward, $reward_qty);
            $this->createRewardUserAssociate($reward, $user, $reward_qty);

        } elseif ($reward->type == Reward::POINTS) {

            $reward_qty = $this->getRewardSize($reward->from, $reward->to);
            $this->updateGiftedQty($reward, $reward_qty);
            $this->createRewardUserAssociate($reward, $user, $reward_qty);

        } elseif ($reward->type == Reward::THINGS) {

            $thing = $this->getAvailableThing($reward);
            $this->createRewardUserAssociate($reward, $user, 1, $thing->id);
            $reward_qty = $thing->name;
        }

        $result = [
            'reward_type' => $reward->type,
            'reward_qty' => $reward_qty,
        ];

        return $result;
    }

    private function getRewardSize(int $from, int $to): int
    {
        $rewardSize = rand($from, $to);

        return $rewardSize;
    }

    /**
     * @param Reward $reward
     * @return Thing
     * @throws \Exception
     */
    private function getAvailableThing(Reward $reward)
    {
        $thing = Thing::getNonGifted();

        try {
            $this->setThingUnavailable($reward, $thing);
        } catch (\Exception $e) {
            Yii::error([
                'message' => $e->getMessage()
            ]);
        }

        return $thing;
    }

    private function setThingUnavailable(Reward $reward, Thing $thing): void
    {
        Thing::updateAll(['gifted' => Thing::GIFTED], ['id' => $thing->id]);

        $this->updateGiftedQty($reward, 1);
    }

    private function updateGiftedQty(Reward $reward, int $qty): void
    {
        $available = 1;

        if ($reward->total <= $reward->gifted_qty + $qty && $reward->type != Reward::POINTS) {
            $available = 0;
        }

        Reward::updateAll([
            'gifted_qty' => $reward->gifted_qty + $qty,
            'available' => $available
        ], ['id' => $reward->id]);
    }

    private function createRewardUserAssociate(Reward $reward, User $user, int $qty = null, int $thing_id = null)
    {
        $link = new RewardUser();
        $link->reward_id = $reward->id;
        $link->user_id = $user->id;
        $link->thing_id = $thing_id;
        $link->qty = $qty;

        $link->save();
    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['login', 'logout'],
                'rules' => [
                    [
                        'actions' => ['login'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ]
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script>
    document.addEventListener("DOMContentLoaded", function (e) {
        let pre = 'Ваш выигрыш: ';
        let accept_button = $('.accept_button');
        let cancel_button = $('.cancel_button');
        let transfer_button = $('.transfer_button');
        let mail_button = $('.mail_button');
        let reward_button = $('.reward_button');

        accept_button.hide();
        cancel_button.hide();
        transfer_button.hide();
        mail_button.hide();

        reward_button.click(function () {
            $.ajax({
                url: '/reward/generate',
                type: 'post',
                dataType: 'json',
                data: {
                    _csrf: yii.getCsrfToken()
                },
                success: function (data) {
                    if (data.reward_type === 1) {
                        $('.user_reward').empty().append(pre + data.reward_qty + ' крон');
                        accept_button.show();
                        accept_button.data('target', data.reward_type);
                        accept_button.data('sum', data.reward_qty);

                        cancel_button.show();
                        cancel_button.data('target', data.reward_type);
                        cancel_button.data('sum', data.reward_qty);

                        transfer_button.show();
                        mail_button.hide();

                    } else if (data.reward_type === 2) {
                        $('.user_reward').empty().append(pre + data.reward_qty + ' баллов');
                        accept_button.show();
                        accept_button.data('target', data.reward_type);
                        accept_button.data('sum', data.reward_qty);

                        cancel_button.show();
                        cancel_button.data('target', data.reward_type);
                        cancel_button.data('sum', data.reward_qty);

                        transfer_button.hide();
                        mail_button.hide();

                    } else if (data.reward_type === 3) {
                        $('.user_reward').empty().append(pre + data.reward_qty);
                        accept_button.hide();

                        cancel_button.show();
                        cancel_button.data('target', data.reward_type);
                        cancel_button.data('sum', data.reward_qty);

                        transfer_button.hide();
                        mail_button.show();
                        mail_button.data('target', data.reward_type);
                    }
                }
            });
        });

        accept_button.click(function () {
            $.ajax({
                url: '/payment/update-user-balance',
                type: 'post',
                dataType: 'json',
                data: {
                    reward_id: $(this).data('target'),
                    sum: $(this).data('sum'),
                    _csrf: yii.getCsrfToken()
                },
                success: function (data) {
                    $('.user_reward').empty().append('ваш счет пополнен');
                    if (data.status === true) {
                        accept_button.hide();
                        cancel_button.hide();
                        transfer_button.hide();
                    }
                }
            });
        });

        cancel_button.click(function () {
            $.ajax({
                url: '/reward/cancel-reward',
                type: 'post',
                dataType: 'json',
                data: {
                    reward_id: $(this).data('target'),
                    _csrf: yii.getCsrfToken()
                },
                success: function (data) {
                    if (data.status === true) {
                        $('.user_reward').empty().append('Вы отказались от выигрыша. Сыграть еще раз?');
                        cancel_button.hide();
                        transfer_button.hide();
                    }
                }
            });
        });

        $('[name="transferForm"]').submit(function (e) {
            e.preventDefault();

            $.ajax({
                url: '/payment/send',
                type: 'post',
                dataType: 'json',
                data: {
                    _csrf: yii.getCsrfToken()
                },
                success: function (data) {
                    if (data.status === true) {
                        $('.user_reward').empty().append('Сумма отправлена');
                        accept_button.hide();
                        cancel_button.hide();
                        transfer_button.hide();
                        mail_button.hide();
                    }
                }
            });
        });

        transfer_button.click(function () {
            $('.transferModal').modal('show');
        });

        mail_button.click(function () {
            $('[name="thing_id"]').val($(this).data('target'));
            $('.shippingModal').modal('show');
        });

        $('[name="shippingForm"]').submit(function (e) {
            e.preventDefault();

            $.ajax({
                url: '/parcel/shipping',
                type: 'post',
                dataType: 'json',
                data: {
                    thing_id: $('[name="thing_id"]').val(),
                    address: $('[name="address"]').val(),
                    _csrf: yii.getCsrfToken()
                },
                success: function (data) {
                    if (data.status === true) {
                        $('.shippingModal').modal('hide');
                        $('.user_reward').empty().append('Выигрыш принят к отправке');
                        accept_button.hide();
                        cancel_button.hide();
                        transfer_button.hide();
                        mail_button.hide();
                    }
                }
            });
        });
    });
</script>

<?php

/* @var $this yii\web\View */

use \yii\helpers\Html;

$this->title = 'Casexe test';

?>
<div class="site-index">

    <div class="jumbotron">
        <?php if (!Yii::$app->user->isGuest) { ?>
            <h1>Congratulations!</h1>

            <p class="lead">Вы выиграли.</p>
            <p>
                <?=
                Html::button('Получите свой приз', [
                    'class' => 'btn btn-lg btn-success reward_button'
                ])
                ?>
            </p>
        <?php } ?>
    </div>

    <div class="body-content">
        <div class="user_reward">

        </div>
        <div class="row user_buttons">
            <button class="btn btn-success accept_button" data-target="" data-sum="">Принять</button>
            <button class="btn btn-danger cancel_button" data-target="" data-sum="">Отклонить</button>
            <button class="btn btn-info transfer_button" data-target="" data-sum="">Перевести на счет</button>
            <button class="btn btn-warning mail_button" data-target="" data-sum="">Отправить почтой</button>
        </div>
    </div>
</div>

<!-- Transafer Modal -->
<div class="modal transferModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content" style="padding: 1.5em;">
            <div class="modal-body">
                <div class="row-fluid">
                    <form class="mt-3" name="transferForm">
                        <div class="row-fluid">
                            <input type="text" name="bank_account" class="form-control" placeholder="счет в банке">
                        </div>
                        <div class="row-fluid">
                            <div class="input-group">
                                <button class="btn btn-success cert-button bank_request">отправить выигрыш</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end Transafer Modal -->

<!-- Shipping Modal -->
<div class="modal shippingModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content" style="padding: 1.5em;">
            <div class="modal-body">
                <div class="row-fluid">
                    <form class="mt-3" name="shippingForm">
                        <div class="row-fluid">
                            <input type="text" name="address" class="form-control" placeholder="Адрес доставки" required>
                        </div>
                        <input type="hidden" name="thing_id" value="">
                        <div class="row-fluid">
                            <div class="input-group">
                                <input type="submit" class="btn btn-success" value="отправить выигрыш">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end Shipping Modal -->

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>